const Color = {
  headerColor: '#e4761e',
  clickableColor: '#e2762e',
  primaryColor: '#03314a',
  primaryButtonColor: '#e4761e',
  errorColor: 'red',
  successColor: 'green',
  inputBorderLineColor: '#7a7a7a',
  borderColor: '#ccc',
  subText: '#aaa',
  horizontalLineColor: '#f2c097',
  verticalLineColor: '#cdcccc',
  disableCardColor: '#cdcccc',
  disabledBtnBg: '#b5b5b5',
  tipBgColor: '#efb71c',
  tipContentBgColor: '#858796',
  btnRemoveBgColor: '#e63636',
  listItemBorderColor: '#c1c1c1',
  cardListItemAvataBg: '#d0cdcd',
  grayColor: '#808080',
  lightGrayColor: '#b5b5b5',          // color for disabled item
  paleGrayColor: '#e6e7e9',
  whiteColor: '#ffffff',
  redColor: '#ff0000',
  blackColor: '#000000',
  lightBlackColor: '#2e2e2e',
  paleBlackColor: '#787878',
  loadingBackgroundColor: 'rgba(227, 107, 51, 0.6)',
};

export default Color;
