const ENDPOINT_LABEL_FIELDNAME = 'endpointLabel';
const ENDPOINT_VALUE_FIELDNAME = 'endpointValue';
const ENDPOINT_SHORTCUT_FIELDNAME = 'endpointShortcut';

export { ENDPOINT_LABEL_FIELDNAME, ENDPOINT_VALUE_FIELDNAME, ENDPOINT_SHORTCUT_FIELDNAME }