export const ERROR_AUTHENTICATION = 'ERROR_AUTHENTICATION';
export const ERROR_ENDPOINT = 'ERROR_ENDPOINT';
export const ERROR_SCORECARD = 'ERROR_SCORECARD';
export const ERROR_NOT_FOUND = 'ERROR_NOT_FOUND';
export const ERROR_UNAUTHORIZED = 'ERROR_UNAUTHORIZED';