export const ERROR_AUTHENTICATION = 'ERROR_AUTHENTICATION';
export const ERROR_ENDPOINT = 'ERROR_ENDPOINT';
export const ERROR_SCORECARD = 'ERROR_SCORECARD';
export const ERROR_INTERNET = 'ERROR_INTERNET';