export const provinces = [
  { name_en: 'banteay meanchey', name_km: 'បន្ទាយមានជ័យ' },
  { name_en: 'battambang', name_km: 'បាត់ដំបង' },
  { name_en: 'kampong cham', name_km: 'កំពង់ចាម' },
  { name_en: 'kampong chhnang', name_km: 'កំពង់ឆ្នាំង' },
  { name_en: 'kampong speu', name_km: 'កំពង់ស្ពឺ' },
  { name_en: 'kampong thom', name_km: 'កំពង់ធំ' },
  { name_en: 'kampot', name_km: 'កំពត' },
  { name_en: 'kandal', name_km: 'កណ្ដាល' },
  { name_en: 'kep', name_km: 'កែប' },
  { name_en: 'koh kong', name_km: 'កោះកុង' },
  { name_en: 'kratie', name_km: 'ក្រចេះ' },
  { name_en: 'mondulkiri', name_km: 'មណ្ឌលគិរី' },
  { name_en: 'phnom penh', name_km: 'ភ្នំពេញ' },
  { name_en: 'preah vihear', name_km: 'ព្រះវិហារ' },
  { name_en: 'prey veng', name_km: 'ព្រៃវែង' },
  { name_en: 'pursat', name_km: 'ពោធិ៍សាត់' },
  { name_en: 'ratanak kiri', name_km: 'រតនគិរី' },
  { name_en: 'siem reap', name_km: 'សៀមរៀប' },
  { name_en: 'preah sihanouk', name_km: 'ព្រះសីហនុ' },
  { name_en: 'stung treng', name_km: 'ស្ទឹងត្រែង' },
  { name_en: 'svay rieng', name_km: 'ស្វាយរៀង' },
  { name_en: 'takeo', name_km: 'តាកែវ' },
  { name_en: 'oddar meanchey', name_km: 'ឧត្ដរមានជ័យ' },
  { name_en: 'pailin', name_km: 'ប៉ៃលិន' },
  { name_en: 'tboung khmum', name_km: 'ត្បូងឃ្មុំ' },
]