const DEFAULT_LANGUAGE = 'km';
const APP_LANGUAGE = 'appLanguage';
const SELECTED_FILTERS = 'selectedFilters'
const ACCORDION_LEFT = 'accordionLeft';
const ACCORDION_RIGHT = 'accordionRight';
const CUSTOM = 'c';
const DEFAULT = 'd';
const TOKEN_SYNCED = 'tokenSynced';
const TOKEN_REGISTERED = 'registeredToken';
const MIN_MODERN_ANDROID_SDK_LEVEL = 35;
const ANDROID_TEN_SDK_VERSION = 29;

export {
  DEFAULT_LANGUAGE,
  APP_LANGUAGE,
  SELECTED_FILTERS,
  ACCORDION_LEFT,
  ACCORDION_RIGHT,
  CUSTOM,
  DEFAULT,
  TOKEN_SYNCED,
  TOKEN_REGISTERED,
  MIN_MODERN_ANDROID_SDK_LEVEL,
  ANDROID_TEN_SDK_VERSION,
};
